services:
  musiclistener:
    working_dir: /var/www/app
    container_name: musiclistener
    environment:
        MUSIC_PORT: 8111
    volumes:
      - ./:/var/www/app
    image: node:slim
    command: "tail -f /dev/null"
